# Generated by Django 5.1.6 on 2025-02-25 17:08

from django.db import migrations
from django.utils.text import slugify


def populate_event_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        base_slug = slugify(event.title)
        slug = base_slug
        counter = 1
        # Keep trying until we find a unique slug
        while Event.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        event.slug = slug
        event.save()


def reverse_populate_event_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.RunPython(
            populate_event_slugs,
            reverse_populate_event_slugs
        ),
    ]
